### PR TITLE
AC Definition

### PR DESCRIPTION
**Pull request by boucadair**
#29

### CODE REVIEW

**Review by lana-wu — COMMENTED** [review]
Are “ethernet interfaces” in the definition are physical interfaces/physical links? To me, the confusion hers is:  In the slice framework definition, the AC can be a physical link or a logical link. If AC can be a physical link, then AC = bearer?

And in "bearer" definition, a bearer can be a wireless or wired link. What are the AC types if the bearer type is wireless?

**Comment by boucadair** [comment]
> Are “ethernet interfaces” in the definition are physical interfaces/physical links? To me, the confusion hers is: In the slice framework definition, the AC can be a physical link or a logical link. If AC can be a physical link, then AC = bearer?

@lana-wu, I fail to see where in the slice framework the AC, it is said that an AC=a physical link. FWIW, here is the full AC definition:

>    Attachment Circuit (AC):  A channel connecting a CE and a PE over
>       which packets that belong to an IETF Network Slice service are
>       exchanged.  An AC is, by definition, technology specific: that is,
>       the AC defines how customer traffic is presented to the provider
>       network.  The customer and provider agree (through configuration)
>       on which values in which combination of layer 2 and layer 3 header
>       and payload fields within a packet identify to which {IETF Network
>       Slice service, connectivity construct, and SLOs/SLEs} that packet
>       is assigned.  The customer and provider may agree on a per {IETF
>       Network Slice service, connectivity construct, and SLOs/SLEs}
>       basis to police or shape traffic on the AC in both the ingress (CE
>       to PE) direction and egress (PE to CE) direction.  This ensures
>       that the traffic is within the capacity profile that is agreed in
>       an IETF Network Slice service.  Excess traffic is dropped by
>       default, unless specific out-of-profile policies are agreed
>       between the customer and the provider.  As described in
>       Section 5.2 the AC may be part of the IETF Network Slice service
>       or may be external to it.  Because SLOs and SLEs characterise the
>       performance of the underlay network between a sending SDP and a
>       set of receiving SDPs, the traffic policers and traffic shapers
>       apply to a specific connectivity construct on an AC.

> And in "bearer" definition, a bearer can be a wireless or wired link. What are the AC types if the bearer type is wireless?

WLAN, 4G, 5G, etc.

**Comment by lana-wu** [comment]
> A channel connecting a CE and a PE

Maybe I am wrong, in my understanding, the channel can be physical interface or logical links .

**Comment by boucadair** [comment]
> > A channel connecting a CE and a PE
> 
> Maybe I am wrong, in my understanding, the channel can be physical interface or logical links .

You are correct if there is no context provided. For the slice case, the "channel" is contextualized as follows: 

> An AC is, by definition, technology specific: that is,
> the AC defines how customer traffic is presented to the provider
> network. The customer and provider agree (through configuration)
> on which values in which combination of layer 2 and layer 3 header
> and payload fields within a packet identify to which {IETF Network
> Slice service, connectivity construct, and SLOs/SLEs} that packet
> is assigned.

**Comment by lana-wu** [comment]
Thanks for clarification. So this is not case for LxSM，site-network-access can be physical or logical links. 
Maybe the definition could add the layer 2 and layer 3 characteristic:
OLD:
An attachment circuit may be the sort of  connection that is usually thought of as a "data link", or it may be a tunnel of some sort;
New:
 An attachment circuit may be the sort of  layer 2 and layer 3 connection that is usually thought of as a "data link";

**Comment by lana-wu** [comment]
One more comment:
In the SAP draft：
Attachment Circuit (AC):
A channel that connects a Customer Edge (CE) to a Provider Edge (PE). The AC may be a **physical or logical link** (Section 6.1 of [[RFC4026](https://www.rfc-editor.org/info/rfc4026)]).

**Comment by boucadair** [comment]
> Maybe the definition could add the layer 2 and layer 3 characteristic:
> OLD:
> An attachment circuit may be the sort of connection that is usually thought of as a "data link", or it may be a tunnel of some sort;
> New:
> An attachment circuit may be the sort of layer 2 and layer 3 connection that is usually thought of as a "data link";

We can't modify that text as this is an excerpt from RFC4364.

You have a valid point that we need to position AC/Bearer vs existing RFCs/Documents.

**Comment by boucadair** [comment]
> One more comment: In the SAP draft： Attachment Circuit (AC): A channel that connects a Customer Edge (CE) to a Provider Edge (PE). The AC may be a **physical or logical link** (Section 6.1 of [[RFC4026](https://www.rfc-editor.org/info/rfc4026)]).

Good catch. I sent this message right now to the list: https://mailarchive.ietf.org/arch/msg/opsawg/_Iiv16zSUnnGuSxywvXlROqh2AI/

**Comment by robric** [comment]
Imho, we should not be specific about CE and PE, since it is sounds technology specific.
The ac permits to connect a generic network service which may be achieved via MPLS (PE, CE), but it can also be provided in a different fashion.



Juniper Business Use Only
Regards,

**Comment by boucadair** [comment]
> Imho, we should not be specific about CE and PE

Agree. We don't have this concern in the proposed definition. 

I think your comment applies to the definition in the slice framework.

**Pull request merged**
