### PR TITLE
Add sample

### PR DESCRIPTION
**Pull request by sbarguil**
#178

### CODE REVIEW

**Comment by boucadair** [comment]
Thanks @sbarguil. 

How this example is different from the one in https://boucadair.github.io/attachment-circuit-model/draft-ietf-opsawg-teas-attachment-circuit.html#name-connect-customer-network-ce?

**Comment by sbarguil** [comment]
> Thanks @sbarguil.
> 
> How this example is different from the one in https://boucadair.github.io/attachment-circuit-model/draft-ietf-opsawg-teas-attachment-circuit.html#name-connect-customer-network-ce?

Just a minor difference: this new sample is pure IP connectivity, without dynamic protocols enabled. @oscargdd, do you foresee any other possible changes I could include?

**Comment by boucadair** [comment]
Thanks @sbarguil. Sent you right now a PR to clean up the example and remove VPN mentions in the figure, in particular

**Comment by boucadair** [comment]
@Samier, I'm planning to reject this PR because it does not reflect the use for interconnection/peering we had initially in mind. 

Can you please inspire from https://datatracker.ietf.org/doc/draft-ramseyer-grow-peering-api/04/ and show how we can use the AC model for this case?

**Comment by boucadair** [comment]
Here is the part to focus on: no need to peer group, bfd, etc. 

        |     +--rw bgp {vpn-common:rtg-bgp}?
        |     |  ..
        |     |  +--rw neighbor* [id]
        |     |     +--rw id                  string
        |     |     +--ro server-reference?   string
        |     |     |       {ac-common:server-assigned-reference}?
        |     |     +--rw remote-address?     inet:ip-address
        |     |     +--rw local-address?      inet:ip-address
        |     |     +--rw local-as?           inet:as-number
        |     |     +--rw peer-as?            inet:as-number
        |     |     +--rw address-family?     identityref
        |     |     +--rw authentication
        |     |     |  +--rw enabled?           boolean
        |     |     |  +--rw keying-material
        |     |     |     +--rw (option)?
        |     |     |        +--:(ao)
        |     |     |        |  +--rw enable-ao?          boolean
        |     |     |        |  +--rw ao-keychain?
        |     |     |        |          key-chain:key-chain-ref
        |     |     |        +--:(md5)
        |     |     |        |  +--rw md5-keychain?
        |     |     |        |          key-chain:key-chain-ref
        |     |     |        +--:(explicit)
        |     |     |           +--rw key-id?             uint32
        |     |     |           +--rw key?                string
        |     |     |           +--rw crypto-algorithm?   identityref
        |     |     +--rw requested-start?    yang:date-and-time
        |     |     +--rw requested-stop?     yang:date-and-time
        |     |     +--ro actual-start?       yang:date-and-time
        |     |     +--ro actual-stop?        yang:date-and-time
        |     |     +--rw status
        |     |     |  +--rw admin-status
        |     |     |  |  +--rw status?        identityref
        |     |     |  |  +--ro last-change?   yang:date-and-time
        |     |     |  +--ro oper-status
        |     |     |     +--ro status?        identityref
        |     |     |     +--ro last-change?   yang:date-and-time

**Comment by sbarguil** [comment]
> @samier, I'm planning to reject this PR because it does not reflect the use for interconnection/peering we had initially in mind.
> 
> Can you please inspire from https://datatracker.ietf.org/doc/draft-ramseyer-grow-peering-api/04/ and show how we can use the AC model for this case?

sure! let me elaborate a new one .

**Comment by sbarguil** [comment]
I will open a new PR for this issue

**Pull request closed without merging**
